# Generated by Django 3.2.10 on 2022-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', max_length=70)),
                ('params', models.CharField(default='', max_length=200)),
                ('chosen', models.BooleanField(default=False)),
            ],
        ),
    ]
