# Generated by Django 3.2.10 on 2022-07-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servstatic', '0002_servicefill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicefill',
            old_name='params',
            new_name='services',
        ),
        migrations.RemoveField(
            model_name='servicefill',
            name='service_name',
        ),
    ]
